#!/usr/bin/env python3
"""
build_rtm.py — Construction script for HALE Feasibility Study RTM v1.0
========================================================================

Allegato A.1 — Requirements Traceability Matrix (RTM) v1.0
Volume 2 — Studio di Fattibilità HALE/VTOL Firmamento Technologies

Genera:
- RTM-v1.0.xlsx      : workbook multi-sheet (14 sheet)
- RTM-v1.0-full.csv  : export piatto per import in DOORS/Jama/Polarion
- A1-RTM-REPORT.md   : report di accompagnamento (~5-8 pagine)

Metodologia: NASA Systems Engineering Handbook Rev 2 (NASA/SP-2016-6105),
             §4.1 Stakeholder Expectations + §4.2 Technical Requirements
             + INCOSE SE Handbook 5th ed. + ISO/IEC/IEEE 15288:2015

Boundary conditions:
- B1: service-only + cooperative Legacoop
- B2: EU sovereign stratospheric layer / "complementare a IRIS²"

Autore: aerospace-systems-engineer (Firmamento Technologies)
Data:   2026-05-17 (M+3 baseline extended → v1.0)
"""

import os
import csv
from datetime import date

import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.formatting.rule import CellIsRule


# =============================================================================
# CONSTANTS — RTM SCHEMA
# =============================================================================

RTM_COLUMNS = [
    "ID",
    "Description",
    "Rationale",
    "Source",
    "Type",
    "Parent",
    "Owner_agent",
    "Priority",
    "VV_Method",
    "VV_Status",
    "Phase",
    "Trade_Study",
    "Risk",
    "Confidence",
    "Falsifying_Observation",
]

# Color palette
COLOR_HEADER = "1F4E78"   # dark blue
COLOR_STNEED = "C6E0B4"   # light green
COLOR_SYR = "BDD7EE"      # light blue
COLOR_SSR = "FFF2CC"      # light yellow
COLOR_IR = "FCE4D6"       # light orange
COLOR_NEGR = "F8CBAD"     # peach / warning
COLOR_VR = "E2EFDA"       # pale green
COLOR_CRITICAL = "C00000" # red (priority H/Critical)
COLOR_HIGH = "ED7D31"     # orange
COLOR_MEDIUM = "FFC000"   # amber
COLOR_LOW = "92D050"      # green

# Confidence color
CONF_COLORS = {
    "high": "C6EFCE",
    "medium": "FFEB9C",
    "low": "FFC7CE",
    "boundary": "BDD7EE",
}

THIN = Side(border_style="thin", color="999999")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)


# =============================================================================
# DATA — STAKEHOLDER NEEDS (extended 17 → 28)
# =============================================================================

STNEEDS = [
    # Baseline 17 from Cap.3 §3.3.2
    ("StNeed-001", "Regione Liguria + PC + ARPA: mappe ad alta risoluzione (≤0.5m GSD) versanti a rischio aree SNAI, settimanale stagione piovosa, mensile altrimenti",
     "Prevenzione rischio idrogeologico", "PSNAI 2025 + DGR Liguria", "StNeed", "-",
     "snai-funding-expert", "H", "-", "-", "Pre-A", "-", "RSK-MKT-003,RSK-OPS-002", "medium",
     "Regione non firma LoI entro M+10 → re-design anchor customer"),
    ("StNeed-002", "PC + VVF + CC Forestali + Enti Parco: alert hotspot termico (≥40°C) entro 5 min, localizzazione GPS + thumbnail",
     "Tempestività intervento antincendio boschivo", "Protocollo PC Liguria + CC Forestali", "StNeed", "-",
     "snai-funding-expert", "H", "-", "-", "Pre-A", "-", "RSK-OPS-002", "medium",
     "PC dichiara latency 5min non sufficiente → re-design SyR-F-003"),
    ("StNeed-003", "PC + Comune Torriglia + Comunità Pentema: connettività mobile/dati backup, disponibilità ≥99% durante crisi",
     "Resilienza comunicazioni in emergenza", "Workshop PC Liguria", "StNeed", "-",
     "snai-funding-expert", "M", "-", "-", "Pre-A", "-", "RSK-REG-005", "medium",
     "AGCOM nega banda licensing → declass UC-003 a opportunistico"),
    ("StNeed-004", "PC + CC Forestali: osservazione aerea persistente + payload termico per SAR persone disperse",
     "Supporto operazioni SAR montane", "Protocollo SAR PC/CC", "StNeed", "-",
     "snai-funding-expert", "M", "-", "-", "Pre-A", "-", "-", "medium",
     "SAR operato in-house VVF, no servizio commerciale → mercato piccolo"),
    ("StNeed-005", "Fabrica + 10 cooperative: mappe topografiche annuali territorio operativo, accuratezza ≤2m",
     "Servizi forestali, agroforestali, manutenzione verde", "Workshop cooperative M+0-3", "StNeed", "-",
     "business-model-strategist", "M", "-", "-", "Pre-A", "-", "-", "low-medium",
     "<8/10 cooperative aderiscono → re-design partnership"),
    ("StNeed-006", "Cooperative agricole: mappe multispettrali NDVI/NDRE quindicinali in stagione vegetativa",
     "Fertirrigazione + rilevamento patogeni", "Workshop cooperative agricole", "StNeed", "-",
     "earth-observation-expert", "M", "-", "-", "Pre-A", "-", "RSK-MKT-004", "low",
     "Pricing target €5-50k/anno < OpEx allocato → UC-005 non scalabile"),
    ("StNeed-007", "Cooperative + comunità rurali: connettività dati ≥10 Mbps in aree senza copertura",
     "Servizi essenziali (e-banking, telemedicina, formazione)", "Dossier SNAI Liguria + indagine 2026", "StNeed", "-",
     "telecom-ntn-payload-expert", "M", "-", "-", "Pre-A", "-", "RSK-MKT-005", "medium",
     "Starlink consumer copre già aree Pentema → competizione"),
    ("StNeed-008", "Comunità Pentema + Garante: no sorveglianza personale, no identificazione volti/targhe in archivi",
     "Privacy + accettabilità sociale", "Principi GDPR + best practice Garante", "StNeed", "-",
     "data-privacy-counsel", "H", "-", "-", "Pre-A", "-", "RSK-TEC-006", "high",
     "DPIA bocciata dal Garante → sospensione UC-001/002 Pentema"),
    ("StNeed-009", "Regione + Enti Parco + comunità: propulsione elettrica/solare, materiali low-impact, rumore <65 dB(A)",
     "Sostenibilità + minimo impatto ambientale", "Reg. UE 2019/945 + ISO 14001 + DGR sostenibilità", "StNeed", "-",
     "esg-sustainability-officer", "H", "-", "-", "Pre-A", "-", "-", "high",
     "Rumore misurato >65 dB(A) a 100m → revisione propulsione/profilo"),
    ("StNeed-010", "Firmamento + Regione + PC: disponibilità ≥80% giorni/anno + reazione emergenza ≤4h",
     "SLA operativi PA + servizi essenziali", "SLA tipici PC + servizi essenziali", "StNeed", "-",
     "vtol-uas-specialist", "H", "-", "-", "Pre-A", "-", "RSK-OPS-001", "medium",
     "Uptime Y1 <60% → re-baseline SLA + revisione contratti"),
    ("StNeed-011", "ENAC + ENAV + Regione: safe behaviour in lost-link/avionica/payload degrade, no incidenti su terzi",
     "Sicurezza operativa BVLOS", "Reg. UE 2019/947 + ENAC Reg.APR Ed.3 + OSO", "StNeed", "-",
     "aviation-regulatory-counsel", "H", "-", "-", "Pre-A", "-", "RSK-TEC-007", "high",
     "Incidente fatale BVLOS Y1-Y2 → revisione completa modello + 432-bis CP"),
    ("StNeed-012", "ENAC + EASA: piena conformità Reg.UE 2019/947 classe Specific con SORA approvata + Ops Manual",
     "Compliance regolatoria europea + nazionale", "Reg. UE 2019/947 + EASA AMC/GM Am.3 (set.2025)", "StNeed", "-",
     "aviation-regulatory-counsel", "H", "-", "-", "Pre-A", "-", "RSK-REG-002", "high",
     "ENAC nega SAIL II-III Pentema → re-design ConOps (VLOS-only)"),
    ("StNeed-013", "AGCOM + MIMIT: tutti link radio in bande regolarmente licenziate + ITU coordination",
     "Compliance spettro radio + ITU", "D.Lgs. 259/2003 + Cap. 5.5", "StNeed", "-",
     "aviation-regulatory-counsel", "H", "-", "-", "Pre-A", "-", "RSK-REG-005", "high",
     "AGCOM rifiuta licensing temporaneo banda LTE tattico → UC-003 declass"),
    ("StNeed-014", "Garante + comunità: trattamento dati personali GDPR-compliant + DPIA per casi d'uso alto rischio",
     "Compliance privacy + protezione dati", "Reg. UE 2016/679 + D.Lgs. 196/2003 novellato", "StNeed", "-",
     "data-privacy-counsel", "H", "-", "-", "Pre-A", "-", "RSK-TEC-006,RSK-REG-016", "high",
     "DPIA pubblica con esito negativo → revisione architettura privacy"),
    ("StNeed-015", "Firmamento + Coopfond: servizi (DaaS, IaaS, canone) anziché vendita asset",
     "Boundary B1 + modello operatore service-only", "Visione strategica (riferimenti/visione-10-anni.md)", "StNeed", "-",
     "business-model-strategist", "H", "-", "-", "Pre-A", "-", "RSK-FIN-002", "boundary",
     "Firma contratto vendita asset → violazione B1 (vedi NegR-B-001)"),
    ("StNeed-016", "Coopfond + Regione: revenue Percorso 6A Y1 ≥ €200k da contratti PA + cooperative",
     "Sostenibilità finanziaria pilota + replicabilità", "Bando Cooding + sostenibilità progetto", "StNeed", "-",
     "financial-cfo-analyst", "H", "-", "-", "Pre-A", "-", "RSK-FIN-003", "medium",
     "Revenue Y1 < €100k → revisione drastica MVP scope"),
    ("StNeed-017", "Firmamento + potenziali partner: scelte 6A producono asset riusabili per 6B + preserva traiettoria EU consortium",
     "Coerenza con visione 10 anni + boundary B2", "Visione strategica progetto", "StNeed", "-",
     "sovereign-strategist", "H", "-", "-", "Pre-A", "-", "-", "boundary",
     "Lock-in tecnologico 6A che impedisce 6B → revisione architetturale"),

    # Extended needs (M+3 baseline expanded for v1.0)
    ("StNeed-018", "Comune Torriglia: deliberazione formale ospitalità pilota + autorizzazioni locali entro M+10",
     "Anchor sito pilota + accettabilità istituzionale locale", "Engagement Comune M+3-6", "StNeed", "-",
     "snai-funding-expert", "H", "-", "-", "Pre-A", "-", "-", "medium",
     "Comune ritira disponibilità → relocate pilota in altra frazione SNAI"),
    ("StNeed-019", "ASL3 Genovese: servizi telemedicina/teleassistenza per residenti Pentema con SLA garantito",
     "Riduzione divario sanitario aree interne", "Indagine ASL3 + DGR Sanità Liguria", "StNeed", "-",
     "snai-funding-expert", "M", "-", "-", "Pre-A", "-", "-", "low-medium",
     "ASL3 non identifica use case scalabile → UC-008 declass"),
    ("StNeed-020", "ACN + Firmamento: posture cybersecurity NIS2-compliant + ISMS Part-IS operativo entro M+9",
     "Compliance NIS2 + Part-IS (Reg.UE 2023/203)", "D.Lgs. 138/2024 + Part-IS", "StNeed", "-",
     "aviation-regulatory-counsel", "H", "-", "-", "Pre-A", "-", "RSK-REG-019,RSK-REG-027", "high",
     "ENAC audit Part-IS rileva non-conformità → sospensione operazioni"),
    ("StNeed-021", "MIMIT + ASI + CIRA: posizionamento Firmamento come nodo italiano in roadmap EU HAPS/IRIS²",
     "Visione strategica B2 + roadmap consorzio EU", "Visione 10 anni + RESERVED-rischi-geopolitici", "StNeed", "-",
     "sovereign-strategist", "M", "-", "-", "Pre-A", "-", "RSK-GEO-002", "boundary",
     "EU consortium si forma senza Firmamento → marginalizzazione Y5-Y7"),
    ("StNeed-022", "DTA Puglia + GATB Grottaglie: accesso test bed BVLOS per qualification piattaforma 6A",
     "Validation test bed certificato", "Partnership DTA + GATB", "StNeed", "-",
     "vtol-uas-specialist", "M", "-", "-", "Pre-A", "-", "-", "medium",
     "GATB non disponibile in finestra M+9-11 → schedule slip 3-6 mesi"),
    ("StNeed-023", "EASA + RMT HAPS: framework certificazione HAPS aperto entro M+36 (Phase B 6B)",
     "Boundary B2 + path certification HALE", "EASA Special Condition pathway + RMT", "StNeed", "-",
     "aviation-regulatory-counsel", "H", "-", "-", "Pre-A", "-", "RSK-TEC-003", "low",
     "EASA non apre RMT HAPS entro M+36 → 6B Phase B rinviato/cancellato"),
    ("StNeed-024", "ENAV: procedure dedicate FL400+ per HALE perennial cross-CTR entro Y4",
     "Operatività italiana 6B perennial", "Reg.UE 2017/373 + ENAV AIP Italy", "StNeed", "-",
     "avionics-gnc-engineer", "M", "-", "-", "Pre-A", "-", "RSK-REG-030", "low",
     "ENAV declina procedure HAPS perennial → 6B Italia bloccato"),
    ("StNeed-025", "Coopfond + Firmamento: revenue diversificato Y2-Y3 (no >40% da un singolo cliente)",
     "Riduzione customer concentration risk + replicabilità", "Best practice startup B2G", "StNeed", "-",
     "business-model-strategist", "M", "-", "-", "Pre-A", "-", "RSK-FIN-004", "medium",
     "Y2 revenue >60% da Regione Liguria → vulnerabilità anchor"),
    ("StNeed-026", "Firmamento: capacity di formazione/upskill 2 PIC + 2 ingegneri payload entro M+12",
     "HR readiness per operations Y1", "Best practice UAS operator + Reg.ENAC", "StNeed", "-",
     "vtol-uas-specialist", "H", "-", "-", "Pre-A", "-", "-", "medium",
     "Turnover Y1 PIC critico → operazioni sospese"),
    ("StNeed-027", "Ente Parco Antola + Aveto: missioni vigilanza ambientale + censimento fauna stagionali",
     "Servizi Enti Parco + biodiversità", "Engagement Enti Parco Liguria", "StNeed", "-",
     "earth-observation-expert", "M", "-", "-", "Pre-A", "-", "-", "low-medium",
     "Enti Parco non sottoscrivono LoI → UC-007 declass"),
    ("StNeed-028", "Firmamento + Coopfond: governance trasparente + audit annuale verso Coopfond + advisory cooperative",
     "Accountability stakeholder + boundary B1", "Bando Coopfond + governance cooperativa", "StNeed", "-",
     "business-model-strategist", "M", "-", "-", "Pre-A", "-", "-", "high",
     "Audit Coopfond rileva non-conformità governance → revisione board"),
]


# =============================================================================
# DATA — SYSTEM REQUIREMENTS (extended 42 → 65)
# =============================================================================

SYREQS = [
    # F — Functional (10 SyR)
    ("SyR-F-001", "Sistema [6A] esegue missioni osservazione aerea con payload EO+IR in area appenninica ligure entro raggio 30 km dalla GS, GSD ≤0.5m @ 500m AGL",
     "Soddisfare StNeed-001+002 con risoluzione cartografica utile", "StNeed-001,StNeed-002", "SyR", "StNeed-001,StNeed-002",
     "aerospace-SE", "H", "A+T", "Open", "Phase A", "TS-PAYLOAD-EO", "RSK-TEC-012", "high",
     "Test flight Pentema mostra GSD reale >0.7m @ 500m AGL → re-spec payload"),
    ("SyR-F-002", "Sistema [6A] esegue missioni BVLOS con autorizzazione SORA SAIL ≤III secondo Reg.UE 2019/947 art.11 + AMC/GM Am.3",
     "Coverage operativa Pentema senza restrizioni VLOS", "StNeed-011,StNeed-012", "SyR", "StNeed-011,StNeed-012",
     "aviation-regulatory-counsel", "H", "I", "Open", "Pre-A", "-", "RSK-REG-002", "medium",
     "ENAC pre-application nega SAIL II-III → re-design ConOps"),
    ("SyR-F-003", "Sistema [6A] rileva hotspot termici ≥40°C in area boschiva + invia alert + thumbnail a GS entro 5 min",
     "Tempestività antincendio + FAR <5%", "StNeed-002", "SyR", "StNeed-002",
     "aerospace-SE", "H", "D+T", "Open", "Phase A", "TS-PAYLOAD-EO", "RSK-OPS-002", "medium",
     "Demo scenario fuoco-pilota mostra latency >8 min o FAR >10% → re-design"),
    ("SyR-F-004", "Sistema [6A] fornisce connettività LTE locale (banda licenziata/ISM) raggio ≥5 km durante emergenze",
     "Resilienza connettività StNeed-003", "StNeed-003", "SyR", "StNeed-003",
     "telecom-ntn-payload-expert", "M", "T", "Open", "Phase A", "-", "RSK-REG-005", "low",
     "AGCOM rifiuta licensing → declass UC-003 a opportunistico"),
    ("SyR-F-005", "Sistema [6B] esegue missioni HAPS persistenti quota 18-21 km, endurance ≥30 giorni continuativi (stagione estiva Y3)",
     "Boundary B2 + visione strategica 6B", "StNeed-017,StNeed-023", "SyR", "StNeed-017,StNeed-023",
     "propulsion-energy-engineer", "H", "A+T", "Open", "Phase B", "TS-PROP-6B", "RSK-TEC-001", "low",
     "Energy balance simulation worst-case mostra <0% margine → seasonal-only fallback"),
    ("SyR-F-006", "Sistema [6A] supporta SAR persone disperse con osservazione aerea persistente >2h + payload IR",
     "Supporto StNeed-004", "StNeed-004", "SyR", "StNeed-004",
     "aerospace-SE", "M", "D", "Open", "Phase A", "-", "-", "medium",
     "Field test SAR scenario VVF mostra payload IR insufficiente notturno → re-spec"),
    ("SyR-F-007", "Sistema [6A] produce ortomosaici multispettrali NDVI/NDRE per cooperative agricole, GSD ≤8cm @ 500m AGL, frequenza quindicinale",
     "Soddisfare StNeed-006", "StNeed-006", "SyR", "StNeed-006",
     "earth-observation-expert", "M", "A+T", "Open", "Phase A", "TS-PAYLOAD-EO", "-", "low",
     "Cooperative agricole pricing reale €5-50k/anno < CapEx allocato → UC-005 non scalabile"),
    ("SyR-F-008", "Sistema [6A] produce mappe topografiche territorio coop con accuratezza posizionale ≤2m, frequenza annuale",
     "Soddisfare StNeed-005", "StNeed-005", "SyR", "StNeed-005",
     "earth-observation-expert", "M", "T", "Open", "Phase A", "-", "-", "medium",
     "Accuratezza misurata >3m in test → revisione GNSS/IMU integration"),
    ("SyR-F-009", "Sistema [6A+6B] supporta vigilanza ambientale Enti Parco con missioni stagionali multi-payload",
     "Soddisfare StNeed-027", "StNeed-027", "SyR", "StNeed-027",
     "earth-observation-expert", "M", "D", "Open", "Phase A", "-", "-", "low-medium",
     "Enti Parco non sottoscrivono LoI → UC-007 declass"),
    ("SyR-F-010", "Sistema [6B Y6+] eroga capacity NTN gNodeB 5G Rel-17/18 con cella ≥10 km diameter, multi-beam (8-32)",
     "Boundary B2 + visione 10 anni Y6+", "StNeed-007,StNeed-017", "SyR", "StNeed-007,StNeed-017",
     "telecom-ntn-payload-expert", "M", "A+T", "Open", "Phase B+", "TS-COMMS", "-", "low",
     "AGCOM non apre licensing HAPS entro WRC-27 → payload telecom rinviato"),

    # P — Performance (12 SyR)
    ("SyR-P-001", "[6A] Autonomia operativa ≥4h volo operativo in condizioni nominali (T -5/+25°C, vento ≤10 m/s, payload pieno)",
     "Coverage missioni tipiche StNeed-001/002/010", "StNeed-001,StNeed-002,StNeed-010", "SyR", "StNeed-001,StNeed-002,StNeed-010",
     "vtol-uas-specialist", "H", "T", "Open", "Phase A", "TS-PLATFORM-6A", "-", "medium",
     "Test flight Pentema mostra autonomia reale <3h con payload pieno → re-spec platform"),
    ("SyR-P-002", "[6A] Velocità di crociera ≥100 km/h ground speed in still air",
     "Efficienza operativa ConOps", "ConOps Cap.3.4.1", "SyR", "ConOps",
     "vtol-uas-specialist", "M", "T", "Open", "Phase A", "TS-PLATFORM-6A", "-", "medium",
     "Test flight mostra cruise <80 km/h → revisione missione/copertura area"),
    ("SyR-P-003", "[6A] Payload utile ≥4 kg (escluso batterie/struttura aggiuntiva)",
     "Multi-sensor mission (EO+IR+SATCOM)", "StNeed-001,StNeed-002,StNeed-003", "SyR", "Multiple StNeeds",
     "vtol-uas-specialist", "H", "I+T", "Open", "Phase A", "TS-PLATFORM-6A", "-", "high",
     "Datasheet vendor confirms payload <3 kg → vendor re-selection"),
    ("SyR-P-004", "[6B] L/D crociera @ 20 km ≥25",
     "Energy balance feasibility 6B", "SyR-F-005", "SyR", "SyR-F-005",
     "aero-structures-engineer", "H", "A+T", "Open", "Phase B", "TS-MATERIAL", "RSK-TEC-002", "medium",
     "Wind tunnel test subscale mostra L/D <20 → re-design wing planform"),
    ("SyR-P-005", "[6B] Energy balance perennial estate (giu-ago, 44°N): margine ≥50%",
     "Feasibility tecnica 6B estate", "SyR-F-005", "SyR", "SyR-F-005",
     "propulsion-energy-engineer", "H", "A", "Open", "Phase B", "TS-PROP-6B", "RSK-TEC-001", "medium-low",
     "Simulazione M+10 mostra margine estate <30% → re-design solar/batt sizing"),
    ("SyR-P-006", "[6B] Energy balance perennial worst-case (solstizio inverno, 44°N): margine ≥30% O seasonal-only mar-ott",
     "Showstopper RSK-TEC-001", "SyR-F-005", "SyR", "SyR-F-005",
     "propulsion-energy-engineer", "H", "A", "Open", "Phase B", "TS-PROP-6B", "RSK-TEC-001", "low",
     "Energy balance simulation 2026 tech mostra margine <0% al 21/12 → seasonal fallback obbligatorio"),
    ("SyR-P-007", "[6A] GSD payload RGB ≤8 cm @ 500m AGL nominale",
     "Risoluzione utile per mapping/SAR", "StNeed-001,StNeed-005", "SyR", "StNeed-001,StNeed-005",
     "earth-observation-expert", "H", "A+T", "Open", "Phase A", "TS-PAYLOAD-EO", "-", "high",
     "GSD reale misurata >15cm → re-spec sensor RGB"),
    ("SyR-P-008", "[6A] GSD payload IR LWIR ≤5m @ 500m AGL termico",
     "Antincendio + SAR thermal detection", "StNeed-002,StNeed-004", "SyR", "StNeed-002,StNeed-004",
     "earth-observation-expert", "H", "A+T", "Open", "Phase A", "TS-PAYLOAD-EO", "-", "medium",
     "GSD termico >8m → IR sensor re-selection"),
    ("SyR-P-009", "[6A] Range C2 link ≥30 km LoS + SATCOM backup non-LoS",
     "Coverage Pentema + shadow zones", "StNeed-001,StNeed-011", "SyR", "StNeed-001,StNeed-011",
     "avionics-gnc-engineer", "H", "T", "Open", "Phase A", "TS-COMMS", "-", "medium",
     "RF range reale <20 km in terreno appenninico → SATCOM primary"),
    ("SyR-P-010", "[6A] Downlink dati payload ≥10 Mbps in raggio 25 km LoS",
     "Real-time imagery + alert", "StNeed-002,StNeed-001", "SyR", "Multiple StNeeds",
     "telecom-ntn-payload-expert", "M", "A+T", "Open", "Phase A", "TS-COMMS", "-", "medium",
     "Throughput <2 Mbps in rain fade → store-and-forward fallback"),
    ("SyR-P-011", "[6A] MTOW ≤55 kg (limite categoria Specific senza requirement aggiuntivi DAL-C completi)",
     "Compliance Reg.UE 2019/947 + sostenibilità SAIL", "SyR-F-002", "SyR", "SyR-F-002",
     "vtol-uas-specialist", "H", "I", "Open", "Pre-A", "TS-PLATFORM-6A", "-", "high",
     "MTOW reale piattaforma >60 kg → re-categorization Certified"),
    ("SyR-P-012", "[6B] MTOW ≤150 kg (range tipico HALE class subscale)",
     "Sizing 6B + path certification", "SyR-F-005", "SyR", "SyR-F-005",
     "aero-structures-engineer", "H", "A+T", "Open", "Phase B", "TS-MATERIAL", "-", "medium",
     "Mass growth >180 kg → re-sizing wing/struttura"),

    # O — Operational (8 SyR)
    ("SyR-O-001", "[6A] Disponibilità operativa ≥80% giorni/anno missioni programmate + ≥99% missioni emergenza con preavviso ≥4h",
     "SLA StNeed-010", "StNeed-010", "SyR", "StNeed-010",
     "vtol-uas-specialist", "H", "D", "Open", "Phase A", "-", "RSK-OPS-001", "medium",
     "Uptime monitoring Y1 mostra <60% → revisione SLA contratti"),
    ("SyR-O-002", "[6A] Tempo reazione emergenza ≤60 min dal call di emergency",
     "StNeed-002/003/004 emergenza", "Multiple StNeeds", "SyR", "Multiple StNeeds",
     "vtol-uas-specialist", "H", "D", "Open", "Phase A", "-", "-", "medium",
     "Reaction time medio Y1 >120 min → revisione SOPs + crew rotation"),
    ("SyR-O-003", "Sistema opera in condizioni ambientali Pentema: T -10/+30°C, umidità 40-90%, vento ≤17 m/s sustained, pioggia ≤10 mm/24h",
     "Caratterizzazione operativa territoriale", "StNeed-010 + caratteristiche territoriali", "SyR", "StNeed-010",
     "vtol-uas-specialist", "H", "I+T", "Open", "Phase A", "-", "RSK-OPS-001", "high",
     "Test ops invernali Pentema mostrano de-icing inadeguato → spec aggiunto"),
    ("SyR-O-004", "[6A] Ground turnaround ≤30 min tra missioni consecutive (battery swap + payload check)",
     "Productivity operativa Y2 scale-up", "StNeed-010", "SyR", "StNeed-010",
     "vtol-uas-specialist", "M", "D", "Open", "Phase A", "-", "-", "medium",
     "Turnaround reale >60 min → revisione spare batteries + crew training"),
    ("SyR-O-005", "[6A] Crew composition: 1 PIC qualificato + 1 observer payload + 1 ground tech, training certificato ENAC",
     "Compliance ENAC + sicurezza StNeed-011 + HR StNeed-026", "StNeed-011,StNeed-026 + Reg.APR Ed.3", "SyR", "StNeed-011,StNeed-026",
     "vtol-uas-specialist", "H", "I", "Open", "Pre-A", "-", "-", "high",
     "Mancanza PIC qualificati EU disponibili → recruitment 6-9 mesi + slip"),
    ("SyR-O-006", "[6A] Operations Manual completo + SOPs operativi + Emergency Procedures redatti entro G3 (M+10)",
     "Compliance ENAC + readiness operativa", "SyR-F-002 + Reg.APR Ed.3", "SyR", "SyR-F-002",
     "aviation-regulatory-counsel", "H", "I", "Open", "Phase A", "-", "RSK-REG-002", "high",
     "Operations Manual rejection ENAC → revisione + slip M+12"),
    ("SyR-O-007", "[6B Phase B] Mission ConOps perennial documentato + handover GATB-Liguria + ENAV LoA",
     "Operatività 6B Phase B + StNeed-024", "SyR-F-005,StNeed-024", "SyR", "SyR-F-005,StNeed-024",
     "avionics-gnc-engineer", "M", "I+D", "Open", "Phase B", "-", "RSK-REG-030", "low",
     "ENAV LoA non firmato entro M+30 → 6B Phase B blocked"),
    ("SyR-O-008", "[6A] Maintenance plan + ricambi 12-mesi stock + supplier qualification documentati",
     "Continuity operativa + supply chain", "SyR-F-001 + best practice", "SyR", "SyR-F-001",
     "vtol-uas-specialist", "H", "I", "Open", "Phase A", "-", "RSK-SUP-001", "medium",
     "Spare parts non disponibili → AOG >30 giorni → SLA violation"),

    # S — Safety (8 SyR)
    ("SyR-S-001", "Lost-Link behaviour: perdita C2 >60s → Return-to-Base autonomo o atterraggio sicuro in area pre-designata",
     "StNeed-011 + Reg.UE 2019/947 OSO #9", "StNeed-011 + Reg.OSO #9", "SyR", "StNeed-011",
     "avionics-gnc-engineer", "H", "D+T", "Open", "Phase A", "-", "RSK-TEC-007", "high",
     "Lost-link test mostra non-conforme OSO #9 SAIL III → mitigation aggiuntiva"),
    ("SyR-S-002", "Parachute recovery o equivalente con impact velocity ≤7 m/s in caso di loss of propulsion",
     "StNeed-011 + SORA M2 mitigation", "StNeed-011 + SORA M2", "SyR", "StNeed-011",
     "vtol-uas-specialist", "H", "T", "Open", "Phase A", "-", "-", "high",
     "Drop test mostra impact velocity >10 m/s → re-sizing parachute"),
    ("SyR-S-003", "Ridondanza N+1 sensori IMU primari + GNSS multi-constellation",
     "SyR-F-002 (SAIL III) + Reg.ENAC art.26 BVLOS", "SyR-F-002 + Reg.ENAC art.26", "SyR", "SyR-F-002",
     "avionics-gnc-engineer", "H", "I", "Open", "Phase A", "-", "-", "high",
     "Single IMU failure during BVLOS → loss of vehicle → re-design redundancy"),
    ("SyR-S-004", "[6B HALE] Detect-And-Avoid (DAA) cooperativo ADS-B IN durante climb/descent CTR",
     "SyR-F-005 + StNeed-024 + ENAV coordination", "SyR-F-005,StNeed-024", "SyR", "SyR-F-005,StNeed-024",
     "avionics-gnc-engineer", "H", "I+D", "Open", "Phase B", "-", "RSK-REG-030", "medium",
     "ENAV richiede DAA non-cooperativo (radar) → re-spec sensors"),
    ("SyR-S-005", "Failure rate target <1e-6 per ora di volo per cause catastrophic (cf. AC 23.1309)",
     "Sicurezza target Specific SAIL III", "SyR-F-002 + AC 23.1309", "SyR", "SyR-F-002",
     "avionics-gnc-engineer", "H", "A", "Open", "Phase B", "-", "RSK-TEC-007", "low",
     "FTA mostra failure rate >1e-5/h → re-design FCS architecture DAL-C"),
    ("SyR-S-006", "Cyber-security C2 link: AES-256 encryption + frequency hopping + crypto authentication",
     "Protezione jamming/spoofing (cf. NIS2)", "StNeed-020 + NIS2 + RSK-TEC-005", "SyR", "StNeed-020",
     "avionics-gnc-engineer", "H", "I+T", "Open", "Phase A", "-", "RSK-TEC-005", "medium",
     "Penetration test mostra C2 link vulnerabile → re-design crypto stack"),
    ("SyR-S-007", "Geofencing software + hardware-enforced no-fly zones (CTR Genova, aree militari, scuole/ospedali)",
     "Safety + compliance Codice Navigazione art.794", "StNeed-011 + Cap.5.16.9", "SyR", "StNeed-011",
     "avionics-gnc-engineer", "H", "I+T", "Open", "Phase A", "-", "-", "high",
     "Drone enters no-fly zone in test → re-design geofence enforcement"),
    ("SyR-S-008", "ATEX compliance hangar storage batterie LiS/Li-ion (Cap.5.16.7)",
     "Sicurezza ground + Direttiva ATEX 2014/34", "StNeed-009 + ATEX", "SyR", "StNeed-009",
     "esg-sustainability-officer", "H", "I", "Open", "Phase A", "-", "RSK-REG-022", "medium",
     "ASL/VVF ispezione classifica hangar zona 1 ATEX → sospensione fino remediation"),

    # E — Environmental & Sustainability (5 SyR)
    ("SyR-E-001", "Propulsione: 100% elettrica per 6A + 100% solare/batterie per 6B",
     "StNeed-009 + boundary sostenibilità", "StNeed-009", "SyR", "StNeed-009",
     "esg-sustainability-officer", "H", "I", "Open", "Phase A", "-", "-", "high",
     "Vendor offre solo configurazioni ibride benzina/elettrico → non conforme"),
    ("SyR-E-002", "Rumore ground sotto rotta tipica (200m AGL cruise): ≤65 dB(A) misurato a 100m laterali",
     "StNeed-009 + Reg.UE 2019/945 acoustic + ISO 3744", "StNeed-009", "SyR", "StNeed-009",
     "esg-sustainability-officer", "H", "T", "Open", "Phase A", "-", "-", "medium",
     "Misurazione mostra >70 dB(A) → re-design rotor/profilo"),
    ("SyR-E-003", "Materiali strutturali: ≥20% in massa con materiali low-impact (compositi fibre naturali, riciclati)",
     "StNeed-009 + narrativa ESG", "StNeed-009", "SyR", "StNeed-009",
     "esg-sustainability-officer", "M", "I", "Open", "Phase B", "TS-MATERIAL", "-", "medium",
     "BoM analysis mostra <10% bio/riciclati → revisione TS-MATERIAL"),
    ("SyR-E-004", "Life Cycle Assessment (LCA) preliminare cradle-to-grave entro M+10 (Vol.2 Allegato dedicato)",
     "ESG due diligence + boundary StNeed-009", "StNeed-009 + best practice ESG", "SyR", "StNeed-009",
     "esg-sustainability-officer", "M", "A", "Open", "Phase A", "-", "-", "medium",
     "LCA non completato entro M+10 → gap deliverable G3"),
    ("SyR-E-005", "End-of-life plan: dismantling + riciclo ≥80% massa entro EOL Y6+",
     "Circular economy + StNeed-009", "StNeed-009 + Direttiva 2008/98/CE", "SyR", "StNeed-009",
     "esg-sustainability-officer", "L", "I", "Open", "Phase B", "-", "-", "low",
     "Vendor non garantisce takeback → revisione strategia EOL"),

    # C — Compliance & Regulatory (12 SyR)
    ("SyR-C-001", "Conformità Reg.UE 2019/947 + 2019/945 + ENAC Reg.APR Ed.3 + Emend.1",
     "Compliance regolatoria UE+IT", "StNeed-012 + Cap.5", "SyR", "StNeed-012",
     "aviation-regulatory-counsel", "H", "I", "Open", "Pre-A", "-", "-", "high",
     "Audit ENAC rileva non-conformità → sospensione operativa"),
    ("SyR-C-002", "Conformità EASA AMC/GM Issue 1 Amendment 3 (SORA 2.5 europea, sett.2025)",
     "Compliance Specific Category + SORA aggiornata", "StNeed-012 + Cap.5.1.4", "SyR", "StNeed-012",
     "aviation-regulatory-counsel", "H", "I", "Open", "Pre-A", "-", "-", "high",
     "SORA application bocciata → revisione + slip M+12"),
    ("SyR-C-003", "Conformità GDPR + D.Lgs.196/2003 novellato + DPIA per casi d'uso high-risk",
     "StNeed-014 + Cap.5.6", "StNeed-014", "SyR", "StNeed-014",
     "data-privacy-counsel", "H", "I", "Open", "Pre-A", "-", "RSK-TEC-006,RSK-REG-016", "high",
     "DPIA bocciata Garante → sospensione UC-001/002/004"),
    ("SyR-C-004", "Conformità NIS2 + D.Lgs.138/2024 + ISMS Part-IS (Reg.UE 2023/203) entro M+9",
     "StNeed-020 + Cap.5.7", "StNeed-020", "SyR", "StNeed-020",
     "aviation-regulatory-counsel", "H", "I+A", "Open", "Phase A", "-", "RSK-REG-019,RSK-REG-027", "high",
     "ACN audit rileva ISMS gap → operations on hold"),
    ("SyR-C-005", "Conformità AS/EN 9100 + ISO 9001 per progettazione/produzione aerospaziale",
     "Bandi pubblici + qualità", "Bandi pubblici Cooding/PNRR", "SyR", "Bandi pubblici",
     "aviation-regulatory-counsel", "M", "I", "Open", "Phase B", "-", "-", "medium",
     "Certificazione non ottenuta entro Y2 → perdita bandi Cooding follow-up"),
    ("SyR-C-006", "Conformità D.Lgs.36/2023 art.41 + Allegato I.7 per PFTE",
     "Bando Cooding + documentazione", "Bando Cooding", "SyR", "Bando Cooding",
     "snai-funding-expert", "H", "I", "Verified", "Pre-A", "-", "-", "high",
     "PFTE non conforme art.41 → bocciatura formale gara"),
    ("SyR-C-007", "Conformità AI Act (Reg.UE 2024/1689) art.5+6 per sistemi onboard ML payload",
     "StNeed-014 + Cap.5.16.1 AI Act", "StNeed-014,Cap.5.16.1", "SyR", "StNeed-014",
     "data-privacy-counsel", "H", "I+A", "Open", "Phase A", "-", "RSK-REG-016", "high",
     "Garante classifica payload IR onboard come 'alto rischio AI Act' → conformity assessment richiesto"),
    ("SyR-C-008", "Conformità AgID/PSN per hosting dati PA (cloud qualificato PSN-listed)",
     "StNeed-020 + Cap.5.16.6", "StNeed-020,Cap.5.16.6", "SyR", "StNeed-020",
     "aviation-regulatory-counsel", "H", "I", "Open", "Phase A", "-", "RSK-REG-021", "high",
     "Dati Pentema in cloud non-PSN → contratti PA rifiutati"),
    ("SyR-C-009", "Conformità Direttiva Macchine (Reg.UE 2023/1230) per ground equipment + GS + carrelli",
     "Cap.5.16.14 + CE marking", "Reg.UE 2023/1230", "SyR", "Cap.5.16.14",
     "aviation-regulatory-counsel", "M", "I", "Open", "Phase B", "-", "RSK-REG-029", "medium",
     "Ente notificato non rilascia CE → ground operations bloccate"),
    ("SyR-C-010", "Assicurazione BVLOS minimo 750.000 DSP (~€900k) SAIL III + RC casco + cyber",
     "Cap.5.16.11 + Reg.UE 285/2004", "Reg.UE 285/2004 + DM 25/02/2022", "SyR", "Cap.5.16.11",
     "financial-cfo-analyst", "H", "I", "Open", "Phase A", "-", "RSK-REG-026", "medium",
     "Premio assicurativo >€100k/anno → modello finanziariamente non sostenibile"),
    ("SyR-C-011", "Conformità ITU-R coordination per banda HAPS (futuro Phase B + WRC-27)",
     "StNeed-013 + Cap.5.5 + StNeed-017", "StNeed-013,Cap.5.5", "SyR", "StNeed-013",
     "telecom-ntn-payload-expert", "M", "I", "Open", "Phase B", "-", "-", "low",
     "ITU-R WRC-27 non assegna banda HAPS in IT → Phase B telecom rinviato"),
    ("SyR-C-012", "Conformità D.Lgs.231/2001 modello organizzativo + 432-bis CP risk management",
     "Cap.5.16.5 + responsabilità penale", "Cap.5.16.5", "SyR", "Cap.5.16.5",
     "aviation-regulatory-counsel", "M", "I", "Open", "Phase A", "-", "RSK-REG-020", "medium",
     "Incidente BVLOS senza modello 231 adeguato → responsabilità amministrativa Firmamento"),

    # Cost — Cost & Business Model (10 SyR)
    ("SyR-Cost-001", "[6A] CapEx Y1 ≤€1.2M (con riserva contingency 30% su €600-900k baseline)",
     "Sostenibilità budget StNeed-015/016", "StNeed-015,StNeed-016 + Cap.8", "SyR", "StNeed-015,StNeed-016",
     "financial-cfo-analyst", "H", "A", "Open", "Phase A", "-", "RSK-FIN-001", "medium",
     "Quotation vendor consolidata >€1.4M → revisione scope o re-funding"),
    ("SyR-Cost-002", "[6A] OpEx run-rate Y2 ≤€450k/anno per operazioni",
     "Sostenibilità modello service-only", "StNeed-015", "SyR", "StNeed-015",
     "financial-cfo-analyst", "H", "A", "Open", "Phase A", "-", "-", "medium",
     "OpEx Y2 reale >€600k (inclusi 3 FTE regolatori) → revisione pricing"),
    ("SyR-Cost-003", "[6A] Revenue Y1 ≥€200k da contratti pluriennali PA + cooperative",
     "Sostenibilità MVP + StNeed-016", "StNeed-016", "SyR", "StNeed-016",
     "financial-cfo-analyst", "H", "D", "Open", "Phase A", "-", "RSK-FIN-003", "medium",
     "Revenue Y1 <€100k → revisione drastica MVP scope"),
    ("SyR-Cost-004", "Modello servizio ricorrente (DaaS/IaaS/canone) — no vendita asset",
     "StNeed-015 + boundary B1", "StNeed-015 + B1", "SyR", "StNeed-015",
     "business-model-strategist", "H", "I", "Open", "Pre-A", "-", "-", "boundary",
     "Firma contratto vendita asset → violazione B1 + NegR-B-001"),
    ("SyR-Cost-005", "Funding mix Y1: ≥60% commitment formale entro G3 (M+10)",
     "Sostenibilità funding plan", "Cap.8 + Bando Cooding", "SyR", "Cap.8",
     "financial-cfo-analyst", "H", "I", "Open", "Pre-A", "-", "RSK-FIN-005", "medium",
     "Funding <40% commitment al G3 → verdetto Hold con re-planning"),
    ("SyR-Cost-006", "Revenue Y2-Y3: customer concentration ≤40% da singolo cliente",
     "StNeed-025 + diversification", "StNeed-025", "SyR", "StNeed-025",
     "business-model-strategist", "M", "A", "Open", "Phase A", "-", "RSK-FIN-004", "medium",
     "Y2 revenue >60% da Regione → vulnerabilità anchor + riduzione score"),
    ("SyR-Cost-007", "Pricing model validato con ≥1 cliente PA (LoI + soglia pricing realistica)",
     "Cap.7.4.4.1 + falsifying observation pricing", "Cap.7 + StNeed-016", "SyR", "Cap.7",
     "business-model-strategist", "H", "D", "Open", "Phase A", "-", "RSK-MKT-001", "medium",
     "Cluster D opera servizi EO regionali a €30-60k/anno → pricing baseline €150k non raggiungibile"),
    ("SyR-Cost-008", "Break-even point Y3-Y4 con NPV>0 @ WACC 12% scenario base",
     "Sostenibilità finanziaria multi-anno", "Cap.8", "SyR", "Cap.8",
     "financial-cfo-analyst", "H", "A", "Open", "Phase A", "-", "-", "medium",
     "Sensitivity worst-case NPV<0 → revisione business model"),
    ("SyR-Cost-009", "Insurance OpEx Y1 ≤€50k/anno (BVLOS RC+casco baseline)",
     "Sostenibilità OpEx Cap.5.16.11", "Cap.5.16.11", "SyR", "Cap.5.16.11",
     "financial-cfo-analyst", "M", "A", "Open", "Phase A", "-", "RSK-REG-026", "low",
     "Premio reale >€100k → modello non sostenibile + revisione SAIL"),
    ("SyR-Cost-010", "[6B] R&D budget Y3-Y5 €5.5-13.5M con multi-source funding (EDF+Horizon+PNRR+equity)",
     "Sostenibilità Phase B 6B", "StNeed-017,StNeed-023 + Cap.8", "SyR", "StNeed-017,StNeed-023",
     "financial-cfo-analyst", "H", "A", "Open", "Phase B", "-", "RSK-FIN-006", "low",
     "Funding commitment <50% al G5 → Phase B deferred"),
]


# =============================================================================
# DATA — SUBSYSTEM REQUIREMENTS - AERO (Aerodinamica & Strutture, 16 SsR)
# =============================================================================

SSR_AERO = [
    ("SsR-AERO-001", "[6B] Wing aspect ratio (AR) ≥25 per minimizzare resistenza indotta",
     "L/D target SyR-P-004", "SyR-P-004", "SsR", "SyR-P-004",
     "aero-structures-engineer", "H", "A", "Open", "Phase B", "TS-MATERIAL", "RSK-TEC-002", "high",
     "Wind tunnel AR=25 mostra flutter critico → re-design AR=20"),
    ("SsR-AERO-002", "[6B] Layup composito longherone alare: CFRP standard cap moduli alti (HM); lino solo strutture secondarie",
     "Trade study TS-MATERIAL + safety strutturale", "SyR-E-003 + SyR-P-004", "SsR", "SyR-E-003,SyR-P-004",
     "aero-structures-engineer", "H", "I+T", "Open", "Phase B", "TS-MATERIAL", "-", "high",
     "Uso lino in longherone primario richiederebbe qualification path 5-10 anni → fuori scope"),
    ("SsR-AERO-003", "[6B] Wing span 25-30m con dihedral 3-5° per stabilità laterale stratosferica",
     "Sizing 6B + stabilità", "SyR-P-004,SyR-P-012", "SsR", "SyR-P-004,SyR-P-012",
     "aero-structures-engineer", "H", "A", "Open", "Phase B", "-", "RSK-TEC-002", "medium",
     "CFD mostra instabilità laterale stratosferica → re-design dihedral"),
    ("SsR-AERO-004", "[6B] Cl_max ≥1.4 alare per low-speed cruise stratosferico",
     "Energy balance + cruise stability", "SyR-P-004", "SsR", "SyR-P-004",
     "aero-structures-engineer", "H", "A+T", "Open", "Phase B", "-", "-", "medium",
     "Cl_max misurato <1.2 → re-spec profilo alare"),
    ("SsR-AERO-005", "[6B] Margine flutter ≥30% velocità di crociera in tutto envelope quota",
     "Aeroelasticità + RSK-TEC-002", "SyR-P-004 + AC 25.629", "SsR", "SyR-P-004",
     "aero-structures-engineer", "H", "A+T", "Open", "Phase B", "TS-MATERIAL", "RSK-TEC-002", "low",
     "Aeroelastic analysis mostra flutter <20% margin → re-design layup/AR"),
    ("SsR-AERO-006", "[6A] Configurazione VTOL ibrido fixed-wing, transizione hover-cruise <30s",
     "ConOps 6A + JOUAV CW-30E baseline", "SyR-F-001,SyR-P-001", "SsR", "SyR-F-001",
     "vtol-uas-specialist", "H", "I+T", "Open", "Phase A", "TS-PLATFORM-6A", "-", "high",
     "Transizione reale >60s → revisione missione operativa"),
    ("SsR-AERO-007", "[6A] MTOW 38 kg + payload max 8 kg conforme vendor JOUAV CW-30E datasheet",
     "TS-PLATFORM-6A baseline", "SyR-P-003,SyR-P-011", "SsR", "SyR-P-003,SyR-P-011",
     "vtol-uas-specialist", "H", "I", "Open", "Phase A", "TS-PLATFORM-6A", "-", "high",
     "Vendor datasheet revised o MTOW reale >50 kg → re-selection"),
    ("SsR-AERO-008", "[6A] Resistenza vento di traverso ≥8 m/s in landing/takeoff",
     "Operatività Pentema condizioni meteo", "SyR-O-003", "SsR", "SyR-O-003",
     "vtol-uas-specialist", "H", "T", "Open", "Phase A", "-", "-", "medium",
     "Test mostra crosswind capability <5 m/s → revisione finestre operative"),
    ("SsR-AERO-009", "[6B] Materiale skin solar panel-friendly (flessibilità + integrazione pannelli flessibili)",
     "Integrazione solare 6B", "SsR-PROP-002", "SsR", "SsR-PROP-002",
     "aero-structures-engineer", "M", "A+T", "Open", "Phase B", "TS-MATERIAL", "-", "medium",
     "Pannelli rigidi non integrabili in skin curvo → re-design wing surface"),
    ("SsR-AERO-010", "[6B] Coda T-tail con stabilizzatore orizzontale altezza ≥1.5m da fusoliera",
     "Aerodinamica + concept Firmamento HALE", "Concept HALE Firmamento", "SsR", "SyR-F-005",
     "aero-structures-engineer", "M", "A", "Open", "Phase B", "-", "-", "medium",
     "CFD mostra interferenza wake → re-design tail"),
    ("SsR-AERO-011", "[6B] Carrello atterraggio retraibile o fixed lightweight con energy absorption",
     "Atterraggio sicuro + mass budget", "SyR-P-012 + ground ops", "SsR", "SyR-P-012",
     "aero-structures-engineer", "M", "A+T", "Open", "Phase B", "-", "-", "medium",
     "Mass carrello >5% MTOW → re-design"),
    ("SsR-AERO-012", "[6A] Materiali compositi CFRP standard + 20% bio-composito secondario (lino in non-primary)",
     "TS-MATERIAL + SyR-E-003", "SyR-E-003", "SsR", "SyR-E-003",
     "aero-structures-engineer", "M", "I", "Open", "Phase B", "TS-MATERIAL", "-", "medium",
     "BoM analysis mostra <10% bio-composito → revisione spec"),
    ("SsR-AERO-013", "[6B] Test in galleria del vento subscale (1:5 o 1:10) entro M+30 per validazione aeroelastica",
     "Validation RSK-TEC-002 + readiness gate G6", "SsR-AERO-005 + RSK-TEC-002", "SsR", "SsR-AERO-005",
     "aero-structures-engineer", "H", "T", "Open", "Phase B", "-", "RSK-TEC-002", "low",
     "Wind tunnel slot non disponibile entro M+30 → schedule slip G6"),
    ("SsR-AERO-014", "[6A] Vita strutturale ≥1000 ore di volo + 500 cicli VTOL transizione",
     "Durability + OpEx maintenance", "SyR-O-008 + best practice UAS", "SsR", "SyR-O-008",
     "aero-structures-engineer", "M", "A+T", "Open", "Phase A", "-", "-", "medium",
     "Fatigue test mostra fatigue life <500h → revisione spec materiale"),
    ("SsR-AERO-015", "[6B] Margine carico statico (limit load × 1.5) verificato per envelope completo",
     "Strutturale + AC 23.337", "SsR-AERO-005", "SsR", "SsR-AERO-005",
     "aero-structures-engineer", "H", "A+T", "Open", "Phase B", "-", "-", "medium",
     "Static load test mostra margine <1.3 → re-design"),
    ("SsR-AERO-016", "[6A+6B] Tolleranza danno (damage tolerance) per impact bird-strike + grandinata",
     "Sicurezza + AC 25.571", "Best practice aviation", "SsR", "SyR-S-001",
     "aero-structures-engineer", "M", "A+T", "Open", "Phase B", "-", "-", "low",
     "Impact test mostra penetrazione bird-strike → re-design leading edge"),
]


# =============================================================================
# DATA — SUBSYSTEM REQUIREMENTS - PROP (Propulsione & Energia, 13 SsR)
# =============================================================================

SSR_PROP = [
    ("SsR-PROP-001", "[6A] Powertrain ibrido VTOL+cruise commerciale TRL ≥8 (vendor: JOUAV/Quantum/FlyingBasket)",
     "Sourcing commerciale + TS-PLATFORM-6A", "SyR-F-001", "SsR", "SyR-F-001",
     "propulsion-energy-engineer", "H", "I", "Open", "Phase A", "TS-PLATFORM-6A", "-", "medium",
     "Vendor non garantisce TRL 8 standardized → re-spec"),
    ("SsR-PROP-002", "[6B] Pannelli solari multi-junction GaAs efficienza η ≥30% (worst case after 1y stratospheric degradation)",
     "Energy balance + SyR-P-005/006", "SyR-P-005,SyR-P-006", "SsR", "SyR-P-005,SyR-P-006",
     "propulsion-energy-engineer", "H", "A+T", "Open", "Phase B", "TS-PROP-6B", "RSK-TEC-001", "medium",
     "Degradation reale >5%/anno → re-sizing solar area"),
    ("SsR-PROP-003", "[6B] Batterie Li-S o Solid-State Li, densità energetica pack ≥350 Wh/kg (TRL ≥5 nel 2027-28 target)",
     "Energy balance worst case + RSK-TEC-001", "SyR-P-006", "SsR", "SyR-P-006",
     "propulsion-energy-engineer", "H", "I+T", "Open", "Phase B", "TS-PROP-6B", "RSK-TEC-001", "low",
     "Mercato 2027 non offre batterie >300 Wh/kg pack → seasonal-only mandatory"),
    ("SsR-PROP-004", "[6A] Batterie LiPo/Li-ion commerciali ≥250 Wh/kg pack, certificate UN38.3 + airworthiness",
     "Autonomia 6A SyR-P-001", "SyR-P-001", "SsR", "SyR-P-001",
     "propulsion-energy-engineer", "H", "I+T", "Open", "Phase A", "-", "-", "high",
     "Cell vendor cambia chimica con effect su autonomia → re-baseline"),
    ("SsR-PROP-005", "[6B] Solar area effettiva ≥45 m² (su wing area ~50 m²)",
     "Energy collection budget", "SyR-P-005 + SsR-PROP-002", "SsR", "SyR-P-005",
     "propulsion-energy-engineer", "H", "A", "Open", "Phase B", "TS-PROP-6B", "-", "medium",
     "Wing surface curvature riduce solar area effective <40 m² → re-sizing"),
    ("SsR-PROP-006", "[6A] Carica batterie ground: charger ≥3 kW + tempo carica ≤90 min per 50→100%",
     "Turnaround SyR-O-004", "SyR-O-004", "SsR", "SyR-O-004",
     "propulsion-energy-engineer", "M", "I+T", "Open", "Phase A", "-", "-", "high",
     "Charger reale 1.5 kW → tempo carica >180 min → revisione spare batt"),
    ("SsR-PROP-007", "[6B] Motori brushless DC efficienza η ≥92% in cruise stratosferico",
     "Power budget HALE", "SyR-P-005,SyR-P-006", "SsR", "Multiple SyR-P",
     "propulsion-energy-engineer", "H", "A+T", "Open", "Phase B", "TS-PROP-6B", "-", "medium",
     "Motor efficiency <88% in test → re-spec motor"),
    ("SsR-PROP-008", "[6B] BMS (Battery Management System) con balancing + thermal control + cycle-life monitoring",
     "Sicurezza batterie + cycle life", "SsR-PROP-003 + ATEX", "SsR", "SsR-PROP-003",
     "propulsion-energy-engineer", "H", "I+T", "Open", "Phase B", "-", "RSK-REG-022", "medium",
     "BMS non rileva thermal runaway iniziale → incidente hangar"),
    ("SsR-PROP-009", "[6A] Sistema propulsione modulare swap-able motors per maintenance/turnaround",
     "OpEx maintenance + turnaround", "SyR-O-004,SyR-O-008", "SsR", "SyR-O-008",
     "propulsion-energy-engineer", "M", "I", "Open", "Phase A", "-", "-", "medium",
     "Motor swap non possibile field → revisione MRO process"),
    ("SsR-PROP-010", "[6B] Power management distribution con voltage bus 270 VDC + secondary 28 VDC per avionica",
     "Architettura elettrica HALE", "SsR-PROP-003 + SsR-AVI-001", "SsR", "SsR-PROP-003",
     "propulsion-energy-engineer", "M", "I+A", "Open", "Phase B", "-", "-", "medium",
     "Voltage bus conflitto con commercial COTS avionica → re-design"),
    ("SsR-PROP-011", "[6A] Backup battery emergency ≥10 min autonomia per RTL/safe landing in caso loss main power",
     "Sicurezza SyR-S-001/002", "SyR-S-001,SyR-S-002", "SsR", "SyR-S-001,SyR-S-002",
     "propulsion-energy-engineer", "H", "I+T", "Open", "Phase A", "-", "-", "high",
     "Backup batt non garantisce 10 min → re-sizing"),
    ("SsR-PROP-012", "[6B] Test cella batterie LiS in camera climatica stratosferica entro M+30 (TRL 5)",
     "Validation RSK-TEC-001 + gate G6", "SsR-PROP-003 + RSK-TEC-001", "SsR", "SsR-PROP-003",
     "propulsion-energy-engineer", "H", "T", "Open", "Phase B", "-", "RSK-TEC-001", "low",
     "Test camera climatica non disponibile → schedule slip TRL maturation"),
    ("SsR-PROP-013", "[6A] Hybrid fuel option (kerosene) escluso per compliance StNeed-009 + boundary ESG",
     "SyR-E-001 100% elettrica", "SyR-E-001", "SsR", "SyR-E-001",
     "propulsion-energy-engineer", "H", "I", "Verified", "Pre-A", "-", "-", "boundary",
     "Vendor offre solo hybrid kerosene → vendor re-selection (no fuel option ammessa)"),
]


# =============================================================================
# DATA — SUBSYSTEM REQUIREMENTS - AVI (Avionica & GNC, 17 SsR)
# =============================================================================

SSR_AVI = [
    ("SsR-AVI-001", "[6A] Autopilota TRL ≥8 con DAL-C minimo per FCS (MicroPilot/UAVOS/Pixhawk Cube modificato)",
     "SAIL III + Reg.ENAC art.26", "SyR-F-002 + Reg.ENAC art.26", "SsR", "SyR-F-002",
     "avionics-gnc-engineer", "H", "I", "Open", "Phase A", "TS-AVI-6A", "-", "medium",
     "Vendor non garantisce DAL-C certification → re-spec autopilot custom"),
    ("SsR-AVI-002", "[6A] C2 link primary RF 2.4/5.8 GHz + secondary SATCOM Iridium Certus per shadow zones Pentema",
     "SyR-S-001 Lost-Link + SyR-P-009", "SyR-S-001,SyR-P-009", "SsR", "SyR-S-001,SyR-P-009",
     "avionics-gnc-engineer", "H", "T", "Open", "Phase A", "TS-COMMS", "-", "medium",
     "RF range Pentema <15 km terreno appenninico → SATCOM primary fallback"),
    ("SsR-AVI-003", "[6A+6B] GNSS dual-frequency multi-constellation (GPS L1/L5+Galileo E1/E5a+GLONASS) con anti-spoofing software",
     "SyR-S-003 sensor redundancy + StNeed-013", "SyR-S-003", "SsR", "SyR-S-003",
     "avionics-gnc-engineer", "H", "I", "Open", "Phase A", "-", "-", "high",
     "GNSS spoofing attack non rilevato → re-design anti-spoofing crypto-based"),
    ("SsR-AVI-004", "[6B HALE] FCS DAL-C completo + ridondanza triple-channel su axe critici",
     "SyR-S-005 + Type Certification Phase B", "SyR-S-005,SyR-F-005", "SsR", "SyR-S-005",
     "avionics-gnc-engineer", "H", "I+T", "Open", "Phase B", "-", "RSK-TEC-003", "low",
     "FCS DAL-C certification path >3 anni → revisione timeline Phase B"),
    ("SsR-AVI-005", "[6A] IMU primary Tactical-Grade (gyro bias stability <1°/h) + IMU secondary commercial",
     "SyR-S-003 ridondanza", "SyR-S-003", "SsR", "SyR-S-003",
     "avionics-gnc-engineer", "H", "I+T", "Open", "Phase A", "-", "-", "high",
     "Tactical IMU >€20k unit → re-spec MEMS high-end con calibration"),
    ("SsR-AVI-006", "[6A] Airdata sensor (pitot+altimeter) ridondato N+1 con cross-check",
     "Safety + envelope protection", "SyR-S-003,SyR-O-003", "SsR", "SyR-S-003",
     "avionics-gnc-engineer", "H", "I+T", "Open", "Phase A", "-", "-", "high",
     "Pitot icing in test invernale → re-design heating"),
    ("SsR-AVI-007", "[6A] Flight Termination System (FTS) attivabile da GS + autonomous trigger su geofence breach",
     "Safety SyR-S-007", "SyR-S-007 + SORA M2", "SsR", "SyR-S-007",
     "avionics-gnc-engineer", "H", "T", "Open", "Phase A", "-", "-", "high",
     "FTS test non termina volo entro 5s → re-design"),
    ("SsR-AVI-008", "[6A] Lost-Link Profile programmato: 60s RTL → 5min loiter → 10min auto-land",
     "SyR-S-001 + OSO #9", "SyR-S-001", "SsR", "SyR-S-001",
     "avionics-gnc-engineer", "H", "D+T", "Open", "Phase A", "-", "RSK-TEC-007", "high",
     "Lost-link demo non rispetta profile temporale → revisione FCS logic"),
    ("SsR-AVI-009", "[6B] DAA ADS-B IN + traffic display + alert pilot remoto",
     "SyR-S-004 + StNeed-024", "SyR-S-004", "SsR", "SyR-S-004",
     "avionics-gnc-engineer", "H", "I+D", "Open", "Phase B", "-", "RSK-REG-030", "medium",
     "ENAV richiede DAA non-cooperativo (radar) → re-spec sensors"),
    ("SsR-AVI-010", "[6A] Encrypted C2 link AES-256 + frequency hopping + crypto authentication",
     "SyR-S-006 cybersecurity", "SyR-S-006", "SsR", "SyR-S-006",
     "avionics-gnc-engineer", "H", "I+T", "Open", "Phase A", "-", "RSK-TEC-005", "medium",
     "Penetration test SaaS C2 mostra crypto debole → re-spec"),
    ("SsR-AVI-011", "[6A] OBC (On-Board Computer) per payload management + edge processing IR/RGB",
     "Edge processing + alert payload", "SyR-F-003 + SsR-PAY-002", "SsR", "SyR-F-003",
     "avionics-gnc-engineer", "M", "I+T", "Open", "Phase A", "-", "-", "medium",
     "OBC compute insufficiente → cloud offload (impatta latency)"),
    ("SsR-AVI-012", "[6A] Mission planner software (open-source MAVProxy/QGC fork o custom)",
     "Operatività + StNeed-005/006 mission tasking", "Multiple StNeeds operativi", "SsR", "SyR-O-001",
     "avionics-gnc-engineer", "M", "I+D", "Open", "Phase A", "-", "-", "high",
     "Mission planner UI non usabile da PA operator → re-design UX"),
    ("SsR-AVI-013", "[6A+6B] Logging & Black Box: registratore dati volo 100% sortita + 30 giorni storage",
     "Safety + post-incident analysis + ENAC compliance", "SyR-S-001 + Reg.ENAC", "SsR", "SyR-S-001",
     "avionics-gnc-engineer", "H", "I", "Open", "Phase A", "-", "-", "high",
     "Black Box capacity <30 days → revisione storage"),
    ("SsR-AVI-014", "[6B] Software flight control firmware compliant DO-178C DAL-C + verification path",
     "Phase B + RSK-TEC-003", "SsR-AVI-004 + DO-178C", "SsR", "SsR-AVI-004",
     "avionics-gnc-engineer", "H", "I+A", "Open", "Phase B", "-", "RSK-TEC-003", "low",
     "DO-178C DAL-C verification effort >18 mesi/3 FTE → schedule slip"),
    ("SsR-AVI-015", "[6A] Health monitoring (HUMS) onboard + GS dashboard real-time anomaly",
     "Maintenance predittiva + safety", "SyR-O-008 + SyR-S-001", "SsR", "SyR-O-008",
     "avionics-gnc-engineer", "M", "D", "Open", "Phase A", "-", "-", "medium",
     "HUMS non rileva anomalie note → revisione thresholds"),
    ("SsR-AVI-016", "[6A] Avionica No-DJI / No-CN per applicazioni PA (compliance NIS2 + Golden Power)",
     "NegR-Tech-002 + StNeed-020", "NegR-Tech-002,StNeed-020", "SsR", "StNeed-020",
     "avionics-gnc-engineer", "H", "I", "Open", "Pre-A", "-", "RSK-SUP-001", "medium",
     "Vendor JOUAV bannato EU → vendor switch EU obbligatorio"),
    ("SsR-AVI-017", "[6B] Software updateable in-flight (OTA) con secure boot + signed firmware",
     "Cybersecurity + maintenance Phase B", "SyR-C-004 + SyR-S-006", "SsR", "SyR-S-006",
     "avionics-gnc-engineer", "M", "I+T", "Open", "Phase B", "-", "-", "low",
     "OTA test mostra vulnerability → re-design crypto chain"),
]


def main():
    print("[build_rtm] Stage 2/4: AERO+PROP+AVI subsystems loaded")
    print(f"  - SsR_AERO: {len(SSR_AERO)}")
    print(f"  - SsR_PROP: {len(SSR_PROP)}")
    print(f"  - SsR_AVI : {len(SSR_AVI)}")


if __name__ == "__main__":
    main()
